[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["src"]
testpaths = ["tests"]

[tool.black]
line-length = 100
target-version = ["py311"]
skip-string-normalization = true

[tool.ruff]
target-version = "py311"
line-length = 100
select = [
	"E",  # pycodestyle
	"F",  # pyflakes
	"I",  # isort
]
ignore = []
fix = true
unsafe-fixes = true

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["digest", "ingest", "parsing", "pipeline", "scrape", "utils", "tools"]
